use crate::core::i18n::Lang;

use anyhow::Result;
use async_trait::async_trait;

#[derive(Debug, Clone)]
pub struct TargetId(pub String);

#[derive(Debug, Clone)]
pub struct MessageId(pub String);

#[derive(Debug, Clone)]
pub struct MessageContent {
    pub text: String,
    pub markup: Option<Markup>,
}

#[derive(Debug, Clone)]
pub struct Markup {
    pub buttons: Vec<Vec<InlineButton>>,
}

#[derive(Debug, Clone)]
pub struct InlineButton {
    pub text: String,
    pub data: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Platform {
    Telegram,
    Discord,
    Matrix,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub struct Principal {
    pub platform: Platform,
    pub subject: String,
}

impl Principal {
    pub fn new(platform: Platform, subject: impl Into<String>) -> anyhow::Result<Self> {
        let subject = subject.into();
        let valid = match platform {
            Platform::Telegram | Platform::Discord => subject
                .parse::<u64>()
                .map(|n| n.to_string() == subject)
                .unwrap_or(false),
            Platform::Matrix => {
                !subject.chars().any(char::is_whitespace)
                    && subject.starts_with('@')
                    && subject
                        .split_once(':')
                        .is_some_and(|(u, h)| u.len() > 1 && !h.is_empty() && !h.contains(':'))
            }
        };
        if !valid {
            anyhow::bail!("invalid principal subject for platform");
        }
        Ok(Self { platform, subject })
    }

    pub fn telegram(id: u64) -> Self {
        Self {
            platform: Platform::Telegram,
            subject: id.to_string(),
        }
    }

    pub fn discord(id: u64) -> Self {
        Self {
            platform: Platform::Discord,
            subject: id.to_string(),
        }
    }

    pub fn matrix(id: &str) -> anyhow::Result<Self> {
        Self::new(Platform::Matrix, id)
    }
}

#[derive(Debug, Clone, Copy)]
pub struct PlatformCapabilities {
    pub can_edit_message: bool,
    pub can_delete_message: bool,
    pub has_inline_keyboard: bool,
    pub has_slash_commands: bool,
    pub has_file_transfer: bool,
}

impl PlatformCapabilities {
    pub const TELEGRAM: Self = Self {
        can_edit_message: true,
        can_delete_message: true,
        has_inline_keyboard: true,
        has_slash_commands: true,
        has_file_transfer: true,
    };

    pub const DISCORD: Self = Self {
        can_edit_message: true,
        can_delete_message: true,
        has_inline_keyboard: true,
        has_slash_commands: true,
        has_file_transfer: false,
    };
}

#[mockall::automock]
#[async_trait]
pub trait BotAdapter: Send + Sync {
    fn platform(&self) -> Platform;
    async fn send_message(&self, target: &TargetId, content: MessageContent) -> Result<MessageId>;
    async fn edit_message(
        &self,
        target: &TargetId,
        msg_id: &MessageId,
        content: MessageContent,
    ) -> Result<()>;
    async fn delete_message(&self, target: &TargetId, msg_id: &MessageId) -> Result<()>;

    async fn answer_callback(
        &self,
        _target: &TargetId,
        _callback_id: &str,
        _text: Option<String>,
    ) -> Result<()> {
        Ok(())
    }

    async fn download_file(&self, _file_id: &str) -> Result<Vec<u8>> {
        anyhow::bail!("platform does not support file download")
    }

    /// Apply OS-level locale/system settings for a chosen language.
    /// Default no-op; only the Telegram adapter performs system operations.
    async fn set_system_locale(&self, _lang: Lang) -> Result<()> {
        Ok(())
    }

    fn capabilities(&self) -> PlatformCapabilities;
}

// MockBotAdapter is auto-generated by mockall above.
// answer_callback and download_file have default implementations so
// mockall does NOT generate expect_ methods for them.
