use anyhow::{Result, anyhow};

pub const MINISIGN_PUBLIC_KEYS: &[&str] = &[
    // TODO: replace with actual public key generated by `minisign -G -W`
    "RWS6qEwIdsvM7UppXGmoZ+nksGYr+sc6POwW2Tdby1mZhpfiipMAu7ts",
];

pub struct MinisigInfo {
    pub trusted_comment: String,
}

pub fn verify_minisign(data: &[u8], sig_str: &str, pub_keys: &[&str]) -> Result<MinisigInfo> {
    let sig =
        minisign_verify::Signature::decode(sig_str).map_err(|e| anyhow!("解析签名失败: {}", e))?;

    for pub_key_str in pub_keys {
        let pub_key = match minisign_verify::PublicKey::from_base64(pub_key_str) {
            Ok(k) => k,
            Err(_) => continue,
        };
        if pub_key.verify(data, &sig, false).is_ok() {
            return Ok(MinisigInfo {
                trusted_comment: sig.trusted_comment().to_string(),
            });
        }
    }

    Err(anyhow!("Minisign 验证失败: 无匹配公钥"))
}

pub fn parse_trusted_comment(comment: &str) -> Result<(String, String)> {
    let parts: Vec<&str> = comment.splitn(2, ':').collect();
    if parts.len() != 2 {
        return Err(anyhow!("无效的可信注释格式: {}", comment));
    }
    Ok((parts[0].to_string(), parts[1].to_string()))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_trusted_comment_valid() {
        let (ver, name) = parse_trusted_comment("v3.1.8:aegis").unwrap();
        assert_eq!(ver, "v3.1.8");
        assert_eq!(name, "aegis");
    }

    #[test]
    fn test_parse_trusted_comment_no_colon() {
        assert!(parse_trusted_comment("no-colon").is_err());
    }

    #[test]
    fn test_parse_trusted_comment_empty() {
        assert!(parse_trusted_comment("").is_err());
    }

    #[test]
    fn test_parse_trusted_comment_multi_colon() {
        let (ver, name) = parse_trusted_comment("v1.0.0:file:extra").unwrap();
        assert_eq!(ver, "v1.0.0");
        assert_eq!(name, "file:extra");
    }
}
