// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/sni.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DomainList stores a list of validated domain names for a country
type DomainList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []string               `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainList) Reset() {
	*x = DomainList{}
	mi := &file_proto_sni_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainList) ProtoMessage() {}

func (x *DomainList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sni_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainList.ProtoReflect.Descriptor instead.
func (*DomainList) Descriptor() ([]byte, []int) {
	return file_proto_sni_proto_rawDescGZIP(), []int{0}
}

func (x *DomainList) GetDomains() []string {
	if x != nil {
		return x.Domains
	}
	return nil
}

var File_proto_sni_proto protoreflect.FileDescriptor

const file_proto_sni_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/sni.proto\x12\x03sni\"&\n" +
	"\n" +
	"DomainList\x12\x18\n" +
	"\adomains\x18\x01 \x03(\tR\adomainsB\x12Z\x10sni_tester/protob\x06proto3"

var (
	file_proto_sni_proto_rawDescOnce sync.Once
	file_proto_sni_proto_rawDescData []byte
)

func file_proto_sni_proto_rawDescGZIP() []byte {
	file_proto_sni_proto_rawDescOnce.Do(func() {
		file_proto_sni_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sni_proto_rawDesc), len(file_proto_sni_proto_rawDesc)))
	})
	return file_proto_sni_proto_rawDescData
}

var file_proto_sni_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_sni_proto_goTypes = []any{
	(*DomainList)(nil), // 0: sni.DomainList
}
var file_proto_sni_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sni_proto_init() }
func file_proto_sni_proto_init() {
	if File_proto_sni_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sni_proto_rawDesc), len(file_proto_sni_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_sni_proto_goTypes,
		DependencyIndexes: file_proto_sni_proto_depIdxs,
		MessageInfos:      file_proto_sni_proto_msgTypes,
	}.Build()
	File_proto_sni_proto = out.File
	file_proto_sni_proto_goTypes = nil
	file_proto_sni_proto_depIdxs = nil
}
