// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: subscription.proto

package sub

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	ConfigIds     []string               `protobuf:"bytes,3,rep,name=config_ids,json=configIds,proto3" json:"config_ids,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Revoked       bool                   `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionToken) Reset() {
	*x = SubscriptionToken{}
	mi := &file_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionToken) ProtoMessage() {}

func (x *SubscriptionToken) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionToken.ProtoReflect.Descriptor instead.
func (*SubscriptionToken) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *SubscriptionToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SubscriptionToken) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SubscriptionToken) GetConfigIds() []string {
	if x != nil {
		return x.ConfigIds
	}
	return nil
}

func (x *SubscriptionToken) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SubscriptionToken) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *SubscriptionToken) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type ProxyConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ConfigId          string                 `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Protocol          string                 `protobuf:"bytes,2,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Host              string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port              uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Password          string                 `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Uuid              string                 `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Sni               string                 `protobuf:"bytes,7,opt,name=sni,proto3" json:"sni,omitempty"`
	PinSha256         string                 `protobuf:"bytes,8,opt,name=pin_sha256,json=pinSha256,proto3" json:"pin_sha256,omitempty"`
	PublicKey         string                 `protobuf:"bytes,9,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ShortId           string                 `protobuf:"bytes,10,opt,name=short_id,json=shortId,proto3" json:"short_id,omitempty"`
	Transport         string                 `protobuf:"bytes,11,opt,name=transport,proto3" json:"transport,omitempty"`
	Path              string                 `protobuf:"bytes,12,opt,name=path,proto3" json:"path,omitempty"`
	Flow              string                 `protobuf:"bytes,13,opt,name=flow,proto3" json:"flow,omitempty"`
	Tag               string                 `protobuf:"bytes,14,opt,name=tag,proto3" json:"tag,omitempty"`
	ObfsType          string                 `protobuf:"bytes,15,opt,name=obfs_type,json=obfsType,proto3" json:"obfs_type,omitempty"`
	ObfsPassword      string                 `protobuf:"bytes,16,opt,name=obfs_password,json=obfsPassword,proto3" json:"obfs_password,omitempty"`
	HopPortStart      uint32                 `protobuf:"varint,17,opt,name=hop_port_start,json=hopPortStart,proto3" json:"hop_port_start,omitempty"`
	HopPortEnd        uint32                 `protobuf:"varint,18,opt,name=hop_port_end,json=hopPortEnd,proto3" json:"hop_port_end,omitempty"`
	Alpn              string                 `protobuf:"bytes,19,opt,name=alpn,proto3" json:"alpn,omitempty"`
	CongestionControl string                 `protobuf:"bytes,20,opt,name=congestion_control,json=congestionControl,proto3" json:"congestion_control,omitempty"`
	CertSha256        string                 `protobuf:"bytes,21,opt,name=cert_sha256,json=certSha256,proto3" json:"cert_sha256,omitempty"`
	Fingerprint       string                 `protobuf:"bytes,22,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`                    // TLS fingerprint (e.g., "chrome")
	Spx               string                 `protobuf:"bytes,23,opt,name=spx,proto3" json:"spx,omitempty"`                                    // Reality short path
	HttpHost          string                 `protobuf:"bytes,24,opt,name=http_host,json=httpHost,proto3" json:"http_host,omitempty"`          // HTTP Host header (WS/XHTTP)
	Mode              string                 `protobuf:"bytes,25,opt,name=mode,proto3" json:"mode,omitempty"`                                  // XHTTP mode (e.g., "auto")
	Extra             string                 `protobuf:"bytes,26,opt,name=extra,proto3" json:"extra,omitempty"`                                // XHTTP extra JSON settings
	HeaderType        string                 `protobuf:"bytes,27,opt,name=header_type,json=headerType,proto3" json:"header_type,omitempty"`    // TCP header type
	ServiceName       string                 `protobuf:"bytes,28,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // gRPC service name
	Authority         string                 `protobuf:"bytes,29,opt,name=authority,proto3" json:"authority,omitempty"`                        // gRPC authority
	Insecure          bool                   `protobuf:"varint,30,opt,name=insecure,proto3" json:"insecure,omitempty"`                         // TLS allowInsecure
	Encryption        string                 `protobuf:"bytes,31,opt,name=encryption,proto3" json:"encryption,omitempty"`                      // VLESS encryption
	ServerName        string                 `protobuf:"bytes,32,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`    // TLS SNI override
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProxyConfig) Reset() {
	*x = ProxyConfig{}
	mi := &file_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfig) ProtoMessage() {}

func (x *ProxyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfig.ProtoReflect.Descriptor instead.
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyConfig) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *ProxyConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ProxyConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ProxyConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ProxyConfig) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *ProxyConfig) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ProxyConfig) GetSni() string {
	if x != nil {
		return x.Sni
	}
	return ""
}

func (x *ProxyConfig) GetPinSha256() string {
	if x != nil {
		return x.PinSha256
	}
	return ""
}

func (x *ProxyConfig) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ProxyConfig) GetShortId() string {
	if x != nil {
		return x.ShortId
	}
	return ""
}

func (x *ProxyConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ProxyConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProxyConfig) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *ProxyConfig) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ProxyConfig) GetObfsType() string {
	if x != nil {
		return x.ObfsType
	}
	return ""
}

func (x *ProxyConfig) GetObfsPassword() string {
	if x != nil {
		return x.ObfsPassword
	}
	return ""
}

func (x *ProxyConfig) GetHopPortStart() uint32 {
	if x != nil {
		return x.HopPortStart
	}
	return 0
}

func (x *ProxyConfig) GetHopPortEnd() uint32 {
	if x != nil {
		return x.HopPortEnd
	}
	return 0
}

func (x *ProxyConfig) GetAlpn() string {
	if x != nil {
		return x.Alpn
	}
	return ""
}

func (x *ProxyConfig) GetCongestionControl() string {
	if x != nil {
		return x.CongestionControl
	}
	return ""
}

func (x *ProxyConfig) GetCertSha256() string {
	if x != nil {
		return x.CertSha256
	}
	return ""
}

func (x *ProxyConfig) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *ProxyConfig) GetSpx() string {
	if x != nil {
		return x.Spx
	}
	return ""
}

func (x *ProxyConfig) GetHttpHost() string {
	if x != nil {
		return x.HttpHost
	}
	return ""
}

func (x *ProxyConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ProxyConfig) GetExtra() string {
	if x != nil {
		return x.Extra
	}
	return ""
}

func (x *ProxyConfig) GetHeaderType() string {
	if x != nil {
		return x.HeaderType
	}
	return ""
}

func (x *ProxyConfig) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ProxyConfig) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *ProxyConfig) GetInsecure() bool {
	if x != nil {
		return x.Insecure
	}
	return false
}

func (x *ProxyConfig) GetEncryption() string {
	if x != nil {
		return x.Encryption
	}
	return ""
}

func (x *ProxyConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type GetConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigsRequest) Reset() {
	*x = GetConfigsRequest{}
	mi := &file_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigsRequest) ProtoMessage() {}

func (x *GetConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigsRequest.ProtoReflect.Descriptor instead.
func (*GetConfigsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *GetConfigsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetConfigsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*ProxyConfig         `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigsResponse) Reset() {
	*x = GetConfigsResponse{}
	mi := &file_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigsResponse) ProtoMessage() {}

func (x *GetConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigsResponse.ProtoReflect.Descriptor instead.
func (*GetConfigsResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *GetConfigsResponse) GetConfigs() []*ProxyConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type GetTokenInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenInfoRequest) Reset() {
	*x = GetTokenInfoRequest{}
	mi := &file_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenInfoRequest) ProtoMessage() {}

func (x *GetTokenInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenInfoRequest.ProtoReflect.Descriptor instead.
func (*GetTokenInfoRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenInfoRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TokenInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Info            *SubscriptionToken     `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	SubscriptionUrl string                 `protobuf:"bytes,2,opt,name=subscription_url,json=subscriptionUrl,proto3" json:"subscription_url,omitempty"`
	ConfigsCount    int64                  `protobuf:"varint,3,opt,name=configs_count,json=configsCount,proto3" json:"configs_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *TokenInfo) GetInfo() *SubscriptionToken {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *TokenInfo) GetSubscriptionUrl() string {
	if x != nil {
		return x.SubscriptionUrl
	}
	return ""
}

func (x *TokenInfo) GetConfigsCount() int64 {
	if x != nil {
		return x.ConfigsCount
	}
	return 0
}

type CreateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	ConfigIds     []string               `protobuf:"bytes,2,rep,name=config_ids,json=configIds,proto3" json:"config_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTokenRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateTokenRequest) GetConfigIds() []string {
	if x != nil {
		return x.ConfigIds
	}
	return nil
}

type TokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *SubscriptionToken     `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *TokenResponse) GetInfo() *SubscriptionToken {
	if x != nil {
		return x.Info
	}
	return nil
}

type ListTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensRequest) Reset() {
	*x = ListTokensRequest{}
	mi := &file_subscription_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensRequest) ProtoMessage() {}

func (x *ListTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensRequest.ProtoReflect.Descriptor instead.
func (*ListTokensRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{8}
}

func (x *ListTokensRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTokensRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*SubscriptionToken   `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTokensResponse) Reset() {
	*x = ListTokensResponse{}
	mi := &file_subscription_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTokensResponse) ProtoMessage() {}

func (x *ListTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTokensResponse.ProtoReflect.Descriptor instead.
func (*ListTokensResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{9}
}

func (x *ListTokensResponse) GetTokens() []*SubscriptionToken {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *ListTokensResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_subscription_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_subscription_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateTokenConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ConfigIds     []string               `protobuf:"bytes,2,rep,name=config_ids,json=configIds,proto3" json:"config_ids,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTokenConfigsRequest) Reset() {
	*x = UpdateTokenConfigsRequest{}
	mi := &file_subscription_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTokenConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTokenConfigsRequest) ProtoMessage() {}

func (x *UpdateTokenConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscription_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTokenConfigsRequest.ProtoReflect.Descriptor instead.
func (*UpdateTokenConfigsRequest) Descriptor() ([]byte, []int) {
	return file_subscription_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateTokenConfigsRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *UpdateTokenConfigsRequest) GetConfigIds() []string {
	if x != nil {
		return x.ConfigIds
	}
	return nil
}

func (x *UpdateTokenConfigsRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_subscription_proto protoreflect.FileDescriptor

const file_subscription_proto_rawDesc = "" +
	"\n" +
	"\x12subscription.proto\x12\fsubscription\"\xb6\x01\n" +
	"\x11SubscriptionToken\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"config_ids\x18\x03 \x03(\tR\tconfigIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\x12\x18\n" +
	"\arevoked\x18\x06 \x01(\bR\arevoked\"\x89\a\n" +
	"\vProxyConfig\x12\x1b\n" +
	"\tconfig_id\x18\x01 \x01(\tR\bconfigId\x12\x1a\n" +
	"\bprotocol\x18\x02 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x1a\n" +
	"\bpassword\x18\x05 \x01(\tR\bpassword\x12\x12\n" +
	"\x04uuid\x18\x06 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03sni\x18\a \x01(\tR\x03sni\x12\x1d\n" +
	"\n" +
	"pin_sha256\x18\b \x01(\tR\tpinSha256\x12\x1d\n" +
	"\n" +
	"public_key\x18\t \x01(\tR\tpublicKey\x12\x19\n" +
	"\bshort_id\x18\n" +
	" \x01(\tR\ashortId\x12\x1c\n" +
	"\ttransport\x18\v \x01(\tR\ttransport\x12\x12\n" +
	"\x04path\x18\f \x01(\tR\x04path\x12\x12\n" +
	"\x04flow\x18\r \x01(\tR\x04flow\x12\x10\n" +
	"\x03tag\x18\x0e \x01(\tR\x03tag\x12\x1b\n" +
	"\tobfs_type\x18\x0f \x01(\tR\bobfsType\x12#\n" +
	"\robfs_password\x18\x10 \x01(\tR\fobfsPassword\x12$\n" +
	"\x0ehop_port_start\x18\x11 \x01(\rR\fhopPortStart\x12 \n" +
	"\fhop_port_end\x18\x12 \x01(\rR\n" +
	"hopPortEnd\x12\x12\n" +
	"\x04alpn\x18\x13 \x01(\tR\x04alpn\x12-\n" +
	"\x12congestion_control\x18\x14 \x01(\tR\x11congestionControl\x12\x1f\n" +
	"\vcert_sha256\x18\x15 \x01(\tR\n" +
	"certSha256\x12 \n" +
	"\vfingerprint\x18\x16 \x01(\tR\vfingerprint\x12\x10\n" +
	"\x03spx\x18\x17 \x01(\tR\x03spx\x12\x1b\n" +
	"\thttp_host\x18\x18 \x01(\tR\bhttpHost\x12\x12\n" +
	"\x04mode\x18\x19 \x01(\tR\x04mode\x12\x14\n" +
	"\x05extra\x18\x1a \x01(\tR\x05extra\x12\x1f\n" +
	"\vheader_type\x18\x1b \x01(\tR\n" +
	"headerType\x12!\n" +
	"\fservice_name\x18\x1c \x01(\tR\vserviceName\x12\x1c\n" +
	"\tauthority\x18\x1d \x01(\tR\tauthority\x12\x1a\n" +
	"\binsecure\x18\x1e \x01(\bR\binsecure\x12\x1e\n" +
	"\n" +
	"encryption\x18\x1f \x01(\tR\n" +
	"encryption\x12\x1f\n" +
	"\vserver_name\x18  \x01(\tR\n" +
	"serverName\")\n" +
	"\x11GetConfigsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"I\n" +
	"\x12GetConfigsResponse\x123\n" +
	"\aconfigs\x18\x01 \x03(\v2\x19.subscription.ProxyConfigR\aconfigs\"+\n" +
	"\x13GetTokenInfoRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x90\x01\n" +
	"\tTokenInfo\x123\n" +
	"\x04info\x18\x01 \x01(\v2\x1f.subscription.SubscriptionTokenR\x04info\x12)\n" +
	"\x10subscription_url\x18\x02 \x01(\tR\x0fsubscriptionUrl\x12#\n" +
	"\rconfigs_count\x18\x03 \x01(\x03R\fconfigsCount\"I\n" +
	"\x12CreateTokenRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"config_ids\x18\x02 \x03(\tR\tconfigIds\"D\n" +
	"\rTokenResponse\x123\n" +
	"\x04info\x18\x01 \x01(\v2\x1f.subscription.SubscriptionTokenR\x04info\"D\n" +
	"\x11ListTokensRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"c\n" +
	"\x12ListTokensResponse\x127\n" +
	"\x06tokens\x18\x01 \x03(\v2\x1f.subscription.SubscriptionTokenR\x06tokens\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"*\n" +
	"\x12RevokeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"/\n" +
	"\x13RevokeTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"o\n" +
	"\x19UpdateTokenConfigsRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"config_ids\x18\x02 \x03(\tR\tconfigIds\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt2\xb2\x01\n" +
	"\x13SubscriptionService\x12O\n" +
	"\n" +
	"GetConfigs\x12\x1f.subscription.GetConfigsRequest\x1a .subscription.GetConfigsResponse\x12J\n" +
	"\fGetTokenInfo\x12!.subscription.GetTokenInfoRequest\x1a\x17.subscription.TokenInfo2\xdd\x02\n" +
	"\fTokenService\x12L\n" +
	"\vCreateToken\x12 .subscription.CreateTokenRequest\x1a\x1b.subscription.TokenResponse\x12O\n" +
	"\n" +
	"ListTokens\x12\x1f.subscription.ListTokensRequest\x1a .subscription.ListTokensResponse\x12R\n" +
	"\vRevokeToken\x12 .subscription.RevokeTokenRequest\x1a!.subscription.RevokeTokenResponse\x12Z\n" +
	"\x12UpdateTokenConfigs\x12'.subscription.UpdateTokenConfigsRequest\x1a\x1b.subscription.TokenResponseB\x1cZ\x1atools/sub-server/proto/subb\x06proto3"

var (
	file_subscription_proto_rawDescOnce sync.Once
	file_subscription_proto_rawDescData []byte
)

func file_subscription_proto_rawDescGZIP() []byte {
	file_subscription_proto_rawDescOnce.Do(func() {
		file_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)))
	})
	return file_subscription_proto_rawDescData
}

var file_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_subscription_proto_goTypes = []any{
	(*SubscriptionToken)(nil),         // 0: subscription.SubscriptionToken
	(*ProxyConfig)(nil),               // 1: subscription.ProxyConfig
	(*GetConfigsRequest)(nil),         // 2: subscription.GetConfigsRequest
	(*GetConfigsResponse)(nil),        // 3: subscription.GetConfigsResponse
	(*GetTokenInfoRequest)(nil),       // 4: subscription.GetTokenInfoRequest
	(*TokenInfo)(nil),                 // 5: subscription.TokenInfo
	(*CreateTokenRequest)(nil),        // 6: subscription.CreateTokenRequest
	(*TokenResponse)(nil),             // 7: subscription.TokenResponse
	(*ListTokensRequest)(nil),         // 8: subscription.ListTokensRequest
	(*ListTokensResponse)(nil),        // 9: subscription.ListTokensResponse
	(*RevokeTokenRequest)(nil),        // 10: subscription.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),       // 11: subscription.RevokeTokenResponse
	(*UpdateTokenConfigsRequest)(nil), // 12: subscription.UpdateTokenConfigsRequest
}
var file_subscription_proto_depIdxs = []int32{
	1,  // 0: subscription.GetConfigsResponse.configs:type_name -> subscription.ProxyConfig
	0,  // 1: subscription.TokenInfo.info:type_name -> subscription.SubscriptionToken
	0,  // 2: subscription.TokenResponse.info:type_name -> subscription.SubscriptionToken
	0,  // 3: subscription.ListTokensResponse.tokens:type_name -> subscription.SubscriptionToken
	2,  // 4: subscription.SubscriptionService.GetConfigs:input_type -> subscription.GetConfigsRequest
	4,  // 5: subscription.SubscriptionService.GetTokenInfo:input_type -> subscription.GetTokenInfoRequest
	6,  // 6: subscription.TokenService.CreateToken:input_type -> subscription.CreateTokenRequest
	8,  // 7: subscription.TokenService.ListTokens:input_type -> subscription.ListTokensRequest
	10, // 8: subscription.TokenService.RevokeToken:input_type -> subscription.RevokeTokenRequest
	12, // 9: subscription.TokenService.UpdateTokenConfigs:input_type -> subscription.UpdateTokenConfigsRequest
	3,  // 10: subscription.SubscriptionService.GetConfigs:output_type -> subscription.GetConfigsResponse
	5,  // 11: subscription.SubscriptionService.GetTokenInfo:output_type -> subscription.TokenInfo
	7,  // 12: subscription.TokenService.CreateToken:output_type -> subscription.TokenResponse
	9,  // 13: subscription.TokenService.ListTokens:output_type -> subscription.ListTokensResponse
	11, // 14: subscription.TokenService.RevokeToken:output_type -> subscription.RevokeTokenResponse
	7,  // 15: subscription.TokenService.UpdateTokenConfigs:output_type -> subscription.TokenResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_subscription_proto_init() }
func file_subscription_proto_init() {
	if File_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscription_proto_rawDesc), len(file_subscription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_subscription_proto_goTypes,
		DependencyIndexes: file_subscription_proto_depIdxs,
		MessageInfos:      file_subscription_proto_msgTypes,
	}.Build()
	File_subscription_proto = out.File
	file_subscription_proto_goTypes = nil
	file_subscription_proto_depIdxs = nil
}
