package main

import (
	"fmt"
	"os"
	"strings"

	"aead.dev/minisign"
)

type MinisigInfo struct {
	TrustedComment string
}

var minisignPublicKeys = []string{
	// TODO: replace with actual public key generated by `minisign -G -W`
	"RWRx............placeholder..................publickey..................==",
}

func verifyMinisign(binaryPath, sigPath string, pubKeys []string) (*MinisigInfo, error) {
	binaryData, err := os.ReadFile(binaryPath)
	if err != nil {
		return nil, fmt.Errorf("读取二进制文件失败: %w", err)
	}

	sigBytes, err := os.ReadFile(sigPath)
	if err != nil {
		return nil, fmt.Errorf("读取签名文件失败: %w", err)
	}

	for _, pubKeyStr := range pubKeys {
		var pubKey minisign.PublicKey
		if err := pubKey.UnmarshalText([]byte(pubKeyStr)); err != nil {
			continue
		}
		if minisign.Verify(pubKey, binaryData, sigBytes) {
			var sig minisign.Signature
			if err := sig.UnmarshalText(sigBytes); err != nil {
				continue
			}
			return &MinisigInfo{
				TrustedComment: sig.TrustedComment,
			}, nil
		}
	}

	return nil, fmt.Errorf("minisign 验证失败: 无匹配公钥")
}

func parseTrustedComment(comment string) (version string, assetName string, err error) {
	parts := strings.SplitN(comment, ":", 2)
	if len(parts) != 2 {
		return "", "", fmt.Errorf("无效的可信注释格式: %s", comment)
	}
	return parts[0], parts[1], nil
}

func findMinisigAsset(release *latestRelease, binaryName string) *releaseAsset {
	sigName := binaryName + ".minisig"
	for i := range release.Assets {
		if release.Assets[i].Name == sigName {
			return &release.Assets[i]
		}
	}
	return nil
}
