name: Dependabot Auto Merge

on:
  pull_request:
    types:
      - labeled

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    if: |
      github.actor == 'dependabot[bot]' &&
      github.event.label.name == 'automerge'

    runs-on: ubuntu-latest

    steps:
      - name: Enable Auto Merge
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr merge \
            --auto \
            --squash \
            "${{ github.event.pull_request.number }}"
