name: Dependabot Auto Merge

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Auto merge Dependabot PR
        if: ${{ github.event.label.name == 'automerge' && github.actor == 'dependabot[bot]' }}
        uses: pascalgn/automerge-action@v0.16.4
        with:
          mergeMethod: squash
          githubToken: ${{ secrets.GITHUB_TOKEN }}
