name: Repo Mirror Sync

on:
  push:
    branches:
      - main
    tags: ["**"]
    paths-ignore:
      - "go/installer/go.mod"
      - "go/installer/go.sum"
      - "sni_tester/go.mod"
      - "sni_tester/go.sum"
      - "rust/tgbot/Cargo.lock"

jobs:
  mirror-codeberg:
    name: Mirror to Codeberg
    if: "!contains(github.event.head_commit.message, 'chore(deps)')"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Mirror to Codeberg
        uses: cssnr/mirror-repository-action@v1.2.0
        with:
          host: https://codeberg.org
          owner: kookybullwhip
          repo: Wuthering_Waves_Private_Server
          username: kookybullwhip
          password: ${{ secrets.CODEBERG_TOKEN }}
          create: true

  mirror-gitlab:
    name: Mirror to GitLab
    if: "!contains(github.event.head_commit.message, 'chore(deps)')"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        uses: cssnr/mirror-repository-action@v1.2.0
        with:
          host: https://gitlab.com
          owner: egfrthtu-group
          repo: wuthering_waves_private_server
          username: EGfrthtu
          password: ${{ secrets.GITLAB_TOKEN }}

  mirror-opencommit:
    name: Mirror to Opencommit
    if: "!contains(github.event.head_commit.message, 'chore(deps)')"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Mirror to Opencommit
        uses: cssnr/mirror-repository-action@v1.2.0
        with:
          host: https://opencommit.eu
          owner: irysdev
          repo: Wuthering_Waves_Private_Server
          username: irysdev
          password: ${{ secrets.OPENCOMMIT_TOKEN }}
          create: true

 mirror-codefloe:
    name: Mirror to Codefloe
    if: "!contains(github.event.head_commit.message, 'chore(deps)')"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0

      - name: Mirror to Codefloe
        uses: cssnr/mirror-repository-action@v1.2.0
        with:
          host: https://codefloe.com
          owner: irysdev
          repo: Wuthering_Waves_Private_Server
          username: irysdev
          password: ${{ secrets.CODEFLOR_TOKEN }}
          create: true
